name: CI
on: [push, pull_request]
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Set Node.js 18
              uses: actions/setup-node@master
              with:
                  node-version: '18'

            - name: yarn install
              run: yarn install

            - name: Verify
              run: yarn verify
